// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/list/[listid]/index.ts";
import * as $2 from "./routes/api/list/[listid]/item/[itemid]/checked.ts";
import * as $3 from "./routes/api/list/[listid]/item/[itemid]/index.ts";
import * as $4 from "./routes/api/list/[listid]/item/[itemid]/move.ts";
import * as $5 from "./routes/api/list/[listid]/item/index.ts";
import * as $6 from "./routes/api/list/index.tsx";
import * as $7 from "./routes/api/ws.ts";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/list.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/ShoppingList.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/list/[listid]/index.ts": $1,
    "./routes/api/list/[listid]/item/[itemid]/checked.ts": $2,
    "./routes/api/list/[listid]/item/[itemid]/index.ts": $3,
    "./routes/api/list/[listid]/item/[itemid]/move.ts": $4,
    "./routes/api/list/[listid]/item/index.ts": $5,
    "./routes/api/list/index.tsx": $6,
    "./routes/api/ws.ts": $7,
    "./routes/index.tsx": $8,
    "./routes/list.tsx": $9,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/ShoppingList.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
