// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/api/_middleware.ts";
import * as $3 from "./routes/api/list/[listid]/index.ts";
import * as $4 from "./routes/api/list/[listid]/item/[itemid]/checked.ts";
import * as $5 from "./routes/api/list/[listid]/item/[itemid]/index.ts";
import * as $6 from "./routes/api/list/[listid]/item/[itemid]/move.ts";
import * as $7 from "./routes/api/list/[listid]/item/index.ts";
import * as $8 from "./routes/api/list/[listid]/status.ts";
import * as $9 from "./routes/api/list/index.tsx";
import * as $10 from "./routes/api/redirect/item/[itemId].ts";
import * as $11 from "./routes/api/search.ts";
import * as $12 from "./routes/api/ws.ts";
import * as $13 from "./routes/index.tsx";
import * as $14 from "./routes/list/[listId].tsx";
import * as $15 from "./routes/list/_middleware.ts";
import * as $16 from "./routes/list/add.tsx";
import * as $17 from "./routes/list/index.tsx";
import * as $18 from "./routes/login.tsx";
import * as $19 from "./routes/search.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/SearchIsland.tsx";
import * as $$2 from "./islands/ShoppingList.tsx";
import * as $$3 from "./islands/Status.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/api/_middleware.ts": $2,
    "./routes/api/list/[listid]/index.ts": $3,
    "./routes/api/list/[listid]/item/[itemid]/checked.ts": $4,
    "./routes/api/list/[listid]/item/[itemid]/index.ts": $5,
    "./routes/api/list/[listid]/item/[itemid]/move.ts": $6,
    "./routes/api/list/[listid]/item/index.ts": $7,
    "./routes/api/list/[listid]/status.ts": $8,
    "./routes/api/list/index.tsx": $9,
    "./routes/api/redirect/item/[itemId].ts": $10,
    "./routes/api/search.ts": $11,
    "./routes/api/ws.ts": $12,
    "./routes/index.tsx": $13,
    "./routes/list/[listId].tsx": $14,
    "./routes/list/_middleware.ts": $15,
    "./routes/list/add.tsx": $16,
    "./routes/list/index.tsx": $17,
    "./routes/login.tsx": $18,
    "./routes/search.tsx": $19,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/SearchIsland.tsx": $$1,
    "./islands/ShoppingList.tsx": $$2,
    "./islands/Status.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
