name: Lint 
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
      - uses: actions/checkout@v3
      - name: "Check if all files are formatted correctly"
        run: "deno fmt --check"
      - name: "Lint"
        if: always()
        run: "deno lint"
